name: clang:ubuntu

on: push

jobs:
  build:
    strategy:
      matrix:
        build_mode: ["Release", "Debug"]
        os: ["macos-15"]
        vulkan: ["1.3.296.0"]
        clang: ["18"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache and Install Dependencies
        id: cache-and-install
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.deps
          key: ${{ matrix.os }}-${{ matrix.vulkan }}-${{ hashFiles('**/lockfiles') }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('vcpkg.json') }}
