name: clang:macos

on: push

jobs:
  build:
    strategy:
      matrix:
        build_mode: ["Release", "Debug"]
        os: ["macos-15"]
        vulkan: ["1.3.296.0"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache and Install Dependencies
        id: cache-and-install
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.deps
          key: ${{ matrix.os }}-${{ matrix.vulkan }}-${{ hashFiles('**/lockfiles') }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('vcpkg.json') }}

      - name: Install Dependencies
        run: |
          brew install llvm molten-vk cmake ninja nasm make

      - name: Install VCPKG
        if: steps.cache-and-install.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git ${{ github.workspace }}/.deps/vcpkg
          cd ${{ github.workspace }}/.deps/vcpkg
          ./bootstrap-vcpkg.sh -disableMetrics

      - name: Install Dependencies, Configure, and Build Ashura
        env:
          CC: /opt/homebrew/opt/llvm/bin/clang
          CXX: /opt/homebrew/opt/llvm/bin/clang++
          VCPKG_ROOT: ${{ github.workspace }}/.deps/vcpkg
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake -DVCPKG_INSTALLED_DIR=${{ env.VCPKG_ROOT }}/installed -DCMAKE_BUILD_TYPE=${{ matrix.build_mode }} -DCMAKE_EXPORT_COMPILE_COMMANDS=1
          make

      - name: Run Tests
        run: |
          cd build
          ./ashura_std_tests
          ./ashura_engine_tests
