name: clang:ubuntu

on: push

jobs:
  build:
    strategy:
      matrix:
        build_mode: ["Release", "Debug"]
        os: ["ubuntu-24.04"]
        vulkan: ["1.3.296.0"]
        clang: ["18"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache and Install Dependencies
        id: cache-and-install
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.deps
          key: ${{ matrix.os }}-${{ matrix.vulkan }}-${{ hashFiles('**/lockfiles') }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('vcpkg.json') }}

      - name: Update Apt
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt dist-upgrade

      - name: Install Build Tools
        run: sudo apt install build-essential ninja-build clang-${{ matrix.clang }} cmake wget libxrandr-dev nasm libstdc++-14-dev

      - name: Install Vulkan SDK
        if: steps.cache-and-install.outputs.cache-hit != 'true'
        run: |
          mkdir .deps
          cd .deps
          wget https://sdk.lunarg.com/sdk/download/${{ matrix.vulkan }}/linux/vulkansdk-linux-x86_64-${{ matrix.vulkan }}.tar.xz
          mkdir VulkanSDK
          tar -xvf vulkansdk-linux-x86_64-${{ matrix.vulkan }}.tar.xz -C VulkanSDK

      - name: Install VCPKG
        if: steps.cache-and-install.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git ${{ github.workspace }}/.deps/vcpkg
          cd ${{ github.workspace }}/.deps/vcpkg
          ./bootstrap-vcpkg.sh -disableMetrics

      - name: Install Dependencies, Configure, and Build Ashura
        env:
          CC: clang-${{ matrix.clang }}
          CXX: clang++-${{ matrix.clang }}
        run: |
          .deps/VulkanSDK/${{ matrix.vulkan }}/setup-env.sh
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/.deps/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_INSTALLED_DIR=${{ github.workspace }}/.deps/vcpkg/installed -DCMAKE_BUILD_TYPE=${{ matrix.build_mode }} -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -GNinja
          ninja

      - name: Run Tests
        run: |
          cd build
          ./ashura_std_tests
          ./ashura_engine_tests
