name: msvc-2019:windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2019

    strategy:
      matrix:
        build_mode: ["Release", "Debug"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache and Install Dependencies
        id: cache-and-install
        uses: actions/cache@v3
        if: always()
        with:
          path: |
            ${{ github.workspace }}/SDKs
            ${{ github.workspace }}/deps
            ${{ github.workspace }}/tools
            SDL3/bin
            SDL3/cmake
            SDL3/include
            SDL3/lib
            ashura/third_party
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}-${{ hashFiles('vcpkg.json') }}-${{ hashFiles('CMakeLists.txt') }}
      
      - name: Install Vulkan SDK
        run: Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.239.0/windows/VulkanSDK-1.3.239.0-Installer.exe" -OutFile "vulkan_installer.exe" && ./vulkan_installer.exe --root ${{ github.workspace }}/SDKs/VulkanSDK/1.3.239.0 --accept-licenses --default-answer --confirm-command install
        if: steps.cache-and-install.outputs.cache-hit != 'true'

      
      - name: Install SDL3
        run: |
          git clone https://github.com/libsdl-org/SDL  ${{ github.workspace }}/deps/SDL
          cd ${{ github.workspace }}/deps/SDL && mkdir build
          cd build && cmake .. -DSDL_STATIC=ON
          cmake --build . --config Release --target install
        if: steps.cache-and-install.outputs.cache-hit != 'true' 

      - name: Install vcpkg
        env:
          VULKAN_SDK: ${{ github.workspace }}/SDKs/VulkanSDK/1.3.239.0
        run: |
          git clone https://github.com/microsoft/vcpkg.git ${{ github.workspace }}/tools/vcpkg
          cd ${{ github.workspace }}/tools/vcpkg && ./bootstrap-vcpkg.bat
          vcpkg integrate install
          copy ${{ github.workspace }}/vcpkg.json .
          vcpkg install --triplet x64-windows 
        if: steps.cache-and-install.outputs.cache-hit != 'true' 

      - name: Configure and build Ashura
        env:
          VULKAN_SDK: ${{ github.workspace }}/SDKs/VulkanSDK/1.3.239.0
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config ${{ matrix.build_mode }}

      - name: Run Ashura Test
        run: cd build/ashura/${{ matrix.build_mode }}/ && ./ashura_test.exe
