name: msvc:windows

on: push

jobs:
  build:
    strategy:
      matrix:
        build_mode: ["Release", "Debug"]
        os: ["windows-2022"]
        vulkan: ["1.3.296.0"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache and Install Dependencies
        id: cache-and-install
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.deps
          key: ${{ matrix.os }}-${{ matrix.vulkan }}-${{ hashFiles('**/lockfiles') }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('vcpkg.json') }}

      - name: Install Vulkan SDK
        if: steps.cache-and-install.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ matrix.vulkan }}/windows/VulkanSDK-${{ matrix.vulkan }}-Installer.exe" -OutFile "vulkan_installer.exe"
          ./vulkan_installer.exe --root ${{ github.workspace }}/.deps/VulkanSDK/${{ matrix.vulkan }} --accept-licenses --default-answer --confirm-command install

      - name: Install VCPKG
        if: steps.cache-and-install.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git ${{ github.workspace }}/.deps/vcpkg
          cd ${{ github.workspace }}/.deps/vcpkg
          ./bootstrap-vcpkg.bat -disableMetrics

      - name: Install Dependencies, Configure, and Build Ashura
        env:
          VULKAN_SDK: ${{ github.workspace }}/.deps/VulkanSDK/${{ matrix.vulkan }}
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/.deps/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_HOST_TRIPLET=x64-windows -DVCPKG_INSTALLED_DIR=${{ github.workspace }}/.deps/vcpkg/installed
          cmake --build . --config ${{ matrix.build_mode }}

      - name: Run Tests
        run: |
          cd build/${{ matrix.build_mode }}/ 
          ./ashura_std_tests.exe
          ./ashura_engine_tests.exe
